### ISSUE TITLE
refactor all boxes to pull from app.vagrantup.com not aws s3

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/vagrant-boxes#11]

**Comment by alan-cugler** [comment]
Do you mean all packer building needs to come from app.vagrantup.com, or the boxes created from packer that are uploaded to app.vagrantup.com need to only reference app.vagrantup.com (which I thought they did)?

**Comment by verhulstm** [comment]
I mean all the "Vagrantfiles" should be pointing to "terminal-labs/[ some box name ]" instead of s3

**Comment by verhulstm** [comment]
no longer relevant
