### ISSUE TITLE
Fedora-Packer error

### ISSUE THREAD

**Issue by alan-cugler** [terminal-labs/vagrant-boxes#14]
Currently building the generic Fedora 25 .box file from packer.
Observations:
I run the following command:
<code> ./packer build config-files/fedora/fedora-25-20gb.json </code>
- The .iso properly downloads from the AWS S3 bucket.
- Starts the virtual machine
Then I get the following error in terminal:
<code> virtualbox-iso: Waiting for SSH to become available... </code>
<code> virtualbox-iso: Timeout waiting for SSH. </code>
<code> virtualbox-iso: Unregistering and deleting virtual machine... </code>
<code> virtualbox-iso: Deleting output directory... </code>
<code> Build 'virtualbox-iso' errored: Timeout waiting for SSH. </code>

I ran the above packer command again with <code -debug</code> included:
It looks like <code> inst.ks=http://10.0.2.2:8722/fedora_preseed.cfg </code> is failing.
I went into the packer directory --> http --> and there is no fedora_preseed.cfg file.
I assume this is the issue? If so, where am I supposed to get the preseed file?

**Comment by verhulstm** [comment]
you have to make the  fedora_preseed.cfg file.

**Comment by verhulstm** [comment]
can we close this issue?
