### ISSUE TITLE
rebuild boxes with Debian 9.3

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/vagrant-boxes#2]

**Comment by alan-cugler** [comment]
Will Debian 8 (jessis) still be maintained after we add in Debian 9 (stretch)? or is Debian 8 going the way of the dodo bird for Rambo & Inflation?

**Comment by verhulstm** [comment]
Debian 8 (jessis) will still be maintained

**Comment by verhulstm** [comment]
done
