### ISSUE TITLE
create gui boxes and separate scripts to build them

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/vagrant-boxes#7]

**Comment by alan-cugler** [comment]
Do you want this for the boxes marked as "full," or also for the empty boxes?

**Comment by alan-cugler** [comment]
Successfully installed the GUI for ubuntu 16.04 server from the code in the Rambo repository on October 4th, 2017.

Notes:
-bare metal server was using ubuntu 16.04 server with GUI installed 
-used "sudo apt-get install ubuntu-desktop"
-No errors installing the GUI
- 4gb of RAM is insufficient for running a GUI Ubuntu server VM within a GUI Ubuntu server host

**Comment by verhulstm** [comment]
4gb of RAM in the guest or in the host?

**Comment by verhulstm** [comment]
We can close this issues we know GUI's can be added in easily enough.

**Comment by nixjdm** [comment]
| We can close this issues we know GUI's can be added in easily enough.

Agreed. We don't need to do this really, and add another entire class of box. We can do this with a Rambo app if we want.
